import { Ionicons } from '@expo/vector-icons';
import { BlurView } from 'expo-blur';
import { LinearGradient } from 'expo-linear-gradient';
import React, { useState } from 'react';
import { Image, ImageBackground, ImageSourcePropType, Pressable, StyleSheet, Text, TextInput, TextInputProps, View } from 'react-native';
import { useAppTheme } from '../context/ThemeContext';
import { Plan, Video } from '../types';

export const AppButton = ({ title, onPress, variant = 'primary', icon, disabled }: { title: string; onPress?: () => void; variant?: 'primary'|'secondary'|'ghost'; icon?: keyof typeof Ionicons.glyphMap; disabled?: boolean }) => {
  const { theme } = useAppTheme();
  const bg = variant === 'primary' ? theme.accent : variant === 'secondary' ? theme.surfaceAlt : 'transparent';
  return <Pressable disabled={disabled} onPress={onPress} style={({ pressed }) => [s.button, { backgroundColor: bg, borderColor: theme.border, opacity: pressed || disabled ? .65 : 1 }]}>
    {icon && <Ionicons name={icon} size={19} color={variant === 'primary' ? '#fff' : theme.text} />}
    <Text style={[s.buttonText, { color: variant === 'primary' ? '#fff' : theme.text }]}>{title}</Text>
  </Pressable>;
};
export const AppInput = ({ label, secureTextEntry, ...props }: TextInputProps & { label?: string }) => {
  const { theme } = useAppTheme(); const [hidden, setHidden] = useState(!!secureTextEntry);
  return <View style={{ gap: 8 }}><Text style={[s.label, { color: theme.text }]}>{label}</Text><View style={[s.inputWrap, { backgroundColor: theme.surface, borderColor: theme.border }]}><TextInput {...props} secureTextEntry={hidden} placeholderTextColor={theme.muted} style={[s.input, { color: theme.text }]} />{secureTextEntry && <Pressable onPress={() => setHidden(v => !v)}><Ionicons name={hidden ? 'eye-outline' : 'eye-off-outline'} size={20} color={theme.muted}/></Pressable>}</View></View>;
};
export const GlassCard = ({ children, style }: React.PropsWithChildren<{ style?: object }>) => { const { theme } = useAppTheme(); return <View style={[s.cardShell, { borderColor: theme.border }, style, { backgroundColor: 'transparent' }]}><BlurView intensity={theme.dark ? 42 : 62} tint={theme.dark ? 'dark' : 'light'} style={StyleSheet.absoluteFill}/><LinearGradient pointerEvents="none" colors={theme.dark ? ['rgba(255,255,255,.13)', 'rgba(255,255,255,.035)', 'rgba(243,107,33,.055)'] : ['rgba(255,255,255,.88)', 'rgba(255,255,255,.54)', 'rgba(247,247,244,.76)']} start={{x:0,y:0}} end={{x:1,y:1}} style={StyleSheet.absoluteFill}/><View pointerEvents="none" style={s.glassHighlight}/><View style={[s.cardContent, { gap: 14 }]}>{children}</View></View>; };
export const AmbientBackground = () => null;
export const SectionHeader = ({ title, action, onPress }: { title: string; action?: string; onPress?: () => void }) => { const { theme } = useAppTheme(); return <View style={s.sectionHead}><Text style={[s.sectionTitle, { color: theme.text }]}>{title}</Text>{action && <Pressable onPress={onPress}><Text style={{ color: theme.accent, fontWeight: '700' }}>{action}</Text></Pressable>}</View>; };
export const StatusBadge = ({ label, tone = 'accent' }: { label: string; tone?: 'accent'|'success'|'neutral' }) => { const { theme } = useAppTheme(); const c = tone === 'success' ? theme.success : tone === 'neutral' ? theme.muted : theme.accent; return <View style={[s.badge, { backgroundColor: c + '18' }]}><View style={[s.dot, { backgroundColor: c }]}/><Text style={{ color: c, fontSize: 12, fontWeight: '800' }}>{label}</Text></View>; };
export const AppHeader = ({ title, subtitle, back, onBack }: { title: string; subtitle?: string; back?: boolean; onBack?: () => void }) => { const { theme } = useAppTheme(); return <View style={s.header}>{back && <Pressable onPress={onBack} style={[s.iconButton, { backgroundColor: theme.surface }]}><Ionicons name="arrow-back" size={21} color={theme.text}/></Pressable>}<View style={{ flex: 1 }}><Text style={[s.headerTitle, { color: theme.text }]}>{title}</Text>{subtitle && <Text style={{ color: theme.muted, marginTop: 3 }}>{subtitle}</Text>}</View></View>; };
export const PlanCard = ({ plan, onDetails, onChoose }: { plan: Plan; onDetails: () => void; onChoose: () => void }) => { const { theme } = useAppTheme(); return <GlassCard style={plan.popular ? { borderColor: theme.accent, borderWidth: 1.5 } : {}}>{plan.popular && <Text style={[s.popular, { backgroundColor: theme.accent }]}>MOST POPULAR</Text>}<View style={s.row}><Text style={[s.planName, { color: theme.text }]}>{plan.name}</Text><Text style={[s.price, { color: theme.text }]}>₹{plan.price}<Text style={{ fontSize: 13, color: theme.muted }}>/mo</Text></Text></View>{plan.benefits.map(x => <View key={x} style={s.benefit}><Ionicons name="checkmark-circle" size={18} color={theme.accent}/><Text style={{ color: theme.muted }}>{x}</Text></View>)}<View style={[s.row, { marginTop: 12 }]}><Pressable onPress={onDetails}><Text style={{ color: theme.text, fontWeight: '700' }}>View details</Text></Pressable><Pressable onPress={onChoose} style={[s.miniButton, { backgroundColor: theme.accent }]}><Text style={{ color: '#fff', fontWeight: '800' }}>Choose plan</Text></Pressable></View></GlassCard>; };
export const ContentCard = ({ video, onPress, wide = false }: { video: Video; onPress: () => void; wide?: boolean }) => { const { theme } = useAppTheme(); return <Pressable onPress={onPress} style={({pressed}) => [s.contentCard, { borderColor: theme.border, opacity: pressed ? .78 : 1 }, wide && { width: 248 }]}><BlurView intensity={theme.dark ? 38 : 55} tint={theme.dark ? 'dark' : 'light'} style={StyleSheet.absoluteFill}/><LinearGradient colors={theme.dark ? ['rgba(255,255,255,.11)','rgba(255,255,255,.025)'] : ['rgba(255,255,255,.8)','rgba(255,255,255,.3)']} style={StyleSheet.absoluteFill}/><ImageBackground source={{ uri: video.thumbnailUrl }} resizeMode="cover" imageStyle={{ opacity: .94 }} style={s.thumb}><View style={[StyleSheet.absoluteFill, { backgroundColor: 'rgba(10,10,9,.24)' }]}/><View style={s.playBubble}><Ionicons name="play" color="#fff" size={20}/></View><StatusBadge label="Unlocked" tone="success"/></ImageBackground><View style={s.contentBody}><Text numberOfLines={1} style={{ color: theme.text, fontSize: 16, fontWeight: '800' }}>{video.title}</Text><Text style={{ color: theme.muted, fontSize: 12 }}>{video.category} · {video.duration}</Text>{video.progress !== undefined && <View style={[s.track, { backgroundColor: theme.surfaceAlt }]}><View style={{ width: `${video.progress * 100}%`, height: 3, backgroundColor: theme.accent, borderRadius: 2 }}/></View>}</View></Pressable>; };
export const EmptyState = ({ title = 'Nothing here yet' }: { title?: string }) => { const { theme } = useAppTheme(); return <GlassCard style={{ alignItems: 'center', gap: 10 }}><Ionicons name="sparkles-outline" size={28} color={theme.accent}/><Text style={{ color: theme.text, fontWeight: '800' }}>{title}</Text></GlassCard>; };
export const LoadingState = () => { const { theme } = useAppTheme(); return <View style={{ gap: 10 }}>{[1,2,3].map(x => <View key={x} style={{ height: 76, borderRadius: 18, backgroundColor: theme.surfaceAlt }}/>)}</View>; };
export const HeroImage = ({ source, style }: { source: ImageSourcePropType; style?: object }) => <Image source={source} style={style} resizeMode="cover"/>;

const s = StyleSheet.create({ button: { minHeight: 54, paddingHorizontal: 20, borderRadius: 18, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8, borderWidth: 1 }, buttonText: { fontSize: 16, fontWeight: '800' }, label: { fontSize: 13, fontWeight: '700' }, inputWrap: { height: 56, borderRadius: 17, borderWidth: 1, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16 }, input: { flex: 1, height: '100%', fontSize: 15 }, cardShell: { borderRadius: 24, borderWidth: 1, overflow: 'hidden', shadowColor: '#171714', shadowOpacity: .1, shadowRadius: 24, shadowOffset: { width: 0, height: 12 }, elevation: 5 }, cardContent: { padding: 20 }, glassHighlight: { position: 'absolute', top: 0, left: 20, right: 20, height: 1, backgroundColor: 'rgba(255,255,255,.92)' }, sectionHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 10, marginBottom: 2 }, sectionTitle: { fontSize: 20, fontWeight: '900', letterSpacing: -.3 }, badge: { flexDirection: 'row', alignItems: 'center', alignSelf: 'flex-start', gap: 5, paddingVertical: 5, paddingHorizontal: 9, borderRadius: 99 }, dot: { width: 6, height: 6, borderRadius: 3 }, header: { minHeight: 64, flexDirection: 'row', gap: 13, alignItems: 'center', marginBottom: 2 }, headerTitle: { fontSize: 28, fontWeight: '900', letterSpacing: -.7 }, iconButton: { width: 43, height: 43, borderRadius: 15, alignItems: 'center', justifyContent: 'center' }, row: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, planName: { fontSize: 24, fontWeight: '900' }, price: { fontSize: 26, fontWeight: '900' }, benefit: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 12 }, popular: { color: '#fff', fontSize: 10, fontWeight: '900', paddingHorizontal: 10, paddingVertical: 5, borderRadius: 10, alignSelf: 'flex-start', marginBottom: 14 }, miniButton: { paddingVertical: 11, paddingHorizontal: 16, borderRadius: 14 }, contentCard: { width: '48%', borderRadius: 21, borderWidth: 1, overflow: 'hidden', shadowColor: '#171714', shadowOpacity: .08, shadowRadius: 16, shadowOffset: { width: 0, height: 8 }, elevation: 3 }, thumb: { height: 116, padding: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, playBubble: { width: 38, height: 38, borderRadius: 19, backgroundColor: 'rgba(0,0,0,.24)', alignItems: 'center', justifyContent: 'center' }, contentBody: { padding: 14, gap: 6 }, track: { height: 3, borderRadius: 2, overflow: 'hidden', marginTop: 6 } });
