"use client";
import {useState} from "react";
const Icon=({children}:{children:React.ReactNode})=><i className="icon">{children}</i>;
function Nav({theme}:{theme:string}){return <nav className={theme}>{[["⌂","Home"],["◈","Programs"],["＋","Coach"],["◷","Progress"],["○","You"]].map((x,i)=><button className={i===0?"active":""} key={x[1]}><Icon>{x[0]}</Icon><span>{x[1]}</span></button>)}</nav>}
function Vitality(){return <div className="phone vitality"><header><div><small>GOOD MORNING</small><h2>Hey, Abhishek 👋</h2></div><button className="avatar">AS<b/></button></header><main><section className="hero"><div><label>YOUR WEEK</label><h1>Stronger every<br/>single day.</h1><p>3 of 5 workouts complete</p></div><div className="ring">60<small>%</small></div><button>Continue workout <b>→</b></button></section><Title over="CHOOSE YOUR GOAL" title="Programs for you"/><div className="cards"><Card cls="peach" icon="⚡" title="Fat loss" text="8 weeks · Beginner"/><Card cls="lilac" icon="◆" title="Muscle gain" text="12 weeks · Intermediate"/></div><section className="coachbox"><div className="faces"><i>AK</i><i>MS</i><i>+8</i></div><small>NEED A LITTLE PUSH?</small><h3>Train 1-on-1 with an expert</h3><p>Personal plans. Real accountability.</p><button>Find my trainer <b>→</b></button></section></main><Nav theme="green"/></div>}
function Card({cls,icon,title,text}:{cls:string,icon:string,title:string,text:string}){return <article className={cls}><b>{icon}</b><h3>{title}</h3><p>{text}</p><strong>Explore ↗</strong></article>}
function Title({over,title}:{over:string,title:string}){return <div className="title"><div><small>{over}</small><h2>{title}</h2></div><button>See all</button></div>}
function Pulse(){const [focus,setFocus]=useState("Build");return <div className="phone pulse"><header><b className="logo">P</b><strong>PULSE<span>+</span></strong><button>♧<i/></button></header><main><section className="blast"><small>WEEK 4 · DAY 2</small><h1>YOUR BODY.<br/><em>YOUR RULES.</em></h1><p>Show up today. Your future self is already proud.</p><button>START TODAY’S SESSION <b>↗</b></button><div className="streak"><b>12</b><span>DAY<br/>STREAK 🔥</span></div></section><Title over="TAILORED FOR YOU" title="Pick your focus"/><div className="tabs">{["Build","Burn","Move","Recover"].map(x=><button className={focus===x?"active":""} onClick={()=>setFocus(x)} key={x}>{x}</button>)}</div><article className="power"><b>0{["Build","Burn","Move","Recover"].indexOf(focus)+1}</b><div><small>{focus.toUpperCase()} SERIES</small><h2>{focus==="Build"?"POWER / 45":focus==="Burn"?"IGNITE / 30":focus==="Move"?"FLOW / 25":"RESET / 20"}</h2><p>Progressive program · 4 weeks</p><span>▰ ▰ ▱ &nbsp; INTERMEDIATE</span></div><button>→</button></article><section className="live"><i>NS</i><div><small>LIVE COACHING</small><h3>Go further, together.</h3><p>Match with a certified coach</p></div><button>→</button></section></main><Nav theme="dark"/></div>}
function Nourish(){return <div className="phone nourish"><header><button className="avatar">AM</button><div><small>Welcome back</small><h2>Abhishek</h2></div><button className="bell">♢<i/></button></header><main><section className="calm"><b className="sun">✦</b><small>TODAY’S INTENTION</small><h1>Move with purpose.<br/>Feel your best.</h1><p>Small steps become lasting change.</p><button>Begin today’s plan <b>→</b></button><div className="week">{["M","T","W","T","F","S","S"].map((x,i)=><i className={i<3?"done":i===3?"today":""} key={i}><b>{i<3?"✓":i===3?"•":""}</b><span>{x}</span></i>)}</div></section><Title over="MADE FOR YOUR GOALS" title="Explore your path"/><div className="paths"><Path cls="rose" icon="↝" over="8 WEEK JOURNEY" title="Lean & energised" text="Fat loss without the burnout"/><Path cls="sage" icon="⌁" over="12 WEEK JOURNEY" title="Strong & grounded" text="Build muscle with confidence"/></div><section className="together"><em>Better, together</em><div><div className="faces"><i>RM</i><i>KS</i><i>+6</i></div><span><h3>Your coach, your journey</h3><p>Real humans. Personal guidance.</p></span><button>Meet coaches</button></div></section></main><Nav theme="soft"/></div>}
function Path({cls,icon,over,title,text}:{cls:string,icon:string,over:string,title:string,text:string}){return <article className={cls}><b>{icon}</b><div><small>{over}</small><h3>{title}</h3><p>{text}</p></div><button>→</button></article>}
export default function Home(){const [v,setV]=useState(1);return <div className={`showcase v${v}`}><aside><div><small>CLIENT PREVIEW</small><b>Fitness app directions</b></div><section>{["Vitality","Pulse","Nourish"].map((x,i)=><button className={v===i+1?"active":""} onClick={()=>setV(i+1)} key={x}><i>0{i+1}</i>{x}</button>)}</section></aside>{v===1?<Vitality/>:v===2?<Pulse/>:<Nourish/>}<footer>Interactive mobile concept · Select a direction above</footer></div>}
