import { Ionicons } from '@expo/vector-icons';
import { NativeStackScreenProps } from '@react-navigation/native-stack';
import React, { useState } from 'react';
import { ImageBackground, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { AppButton, AppHeader, AppInput } from '../components/ui';
import { useAuth } from '../context/AuthContext';
import { useAppTheme } from '../context/ThemeContext';
import { RootStackParamList } from '../types';
const hero = require('../../assets/fitness-hero.png');
type P<N extends keyof RootStackParamList> = NativeStackScreenProps<RootStackParamList, N>;
const messageOf = (error: unknown) => error instanceof Error ? error.message : 'Something went wrong. Please try again.';

export const SplashScreen = () => { const { theme } = useAppTheme(); return <SafeAreaView style={[s.center, { backgroundColor: theme.background }]}><View style={[s.logo, { backgroundColor: theme.accent }]}><Ionicons name="pulse" color="#fff" size={35}/></View><Text style={[s.brand, { color: theme.text }]}>FITORA</Text><Text style={{ color: theme.muted }}>Move with purpose.</Text><View style={[s.loader, { backgroundColor: theme.surfaceAlt }]}><View style={{ width: '55%', height: 4, borderRadius: 4, backgroundColor: theme.accent }}/></View></SafeAreaView>; };
export const WelcomeScreen = ({ navigation }: P<'Welcome'>) => { const { theme } = useAppTheme(); return <View style={{ flex: 1, backgroundColor: theme.background }}><ImageBackground source={hero} style={{ flex: 1 }}><View style={s.overlay}/><SafeAreaView style={s.welcome}><View style={s.brandRow}><View style={[s.logoSmall, { backgroundColor: theme.accent }]}><Ionicons name="pulse" color="#fff" size={19}/></View><Text style={s.brandWhite}>FITORA</Text></View><View style={{ gap: 15 }}><Text style={s.heroTitle}>Your strongest self starts here.</Text><Text style={s.heroCopy}>Premium training that fits your pace, your goals, and your life.</Text><AppButton title="Get started" onPress={() => navigation.navigate('Register')} icon="arrow-forward"/><AppButton title="I already have an account" variant="secondary" onPress={() => navigation.navigate('Login')}/></View></SafeAreaView></ImageBackground></View>; };
const AuthShell = ({ title, subtitle, children, onBack }: React.PropsWithChildren<{ title: string; subtitle: string; onBack: () => void }>) => { const { theme } = useAppTheme(); return <SafeAreaView style={[s.safe, { backgroundColor: theme.background }]}><ScrollView contentContainerStyle={s.form} keyboardShouldPersistTaps="handled"><AppHeader title={title} subtitle={subtitle} back onBack={onBack}/>{children}</ScrollView></SafeAreaView>; };

export const LoginScreen = ({ navigation }: P<'Login'>) => {
  const { requestLoginOtp } = useAuth(); const [email, setEmail] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const submit = async () => { const normalizedEmail = email.trim().toLowerCase(); if (!/^\S+@\S+\.\S+$/.test(normalizedEmail)) { setError('Enter a valid registered email address.'); return; } setBusy(true); setError(''); try { await requestLoginOtp(normalizedEmail); navigation.navigate('VerifyEmailOtp', { email: normalizedEmail, mode: 'login' }); } catch (e) { const message = messageOf(e); setError(message.toLowerCase().includes('signups not allowed') ? 'No account was found for this email. Please create an account first.' : message); } finally { setBusy(false); } };
  return <AuthShell title="Welcome back" subtitle="Enter your registered email and we’ll send you a login code." onBack={() => navigation.goBack()}><AppInput label="Email" placeholder="you@example.com" value={email} onChangeText={setEmail} keyboardType="email-address" autoCapitalize="none" autoComplete="email"/>{!!error && <Text style={s.error}>{error}</Text>}<AppButton title={busy ? 'Sending code…' : 'Send login code'} disabled={busy} onPress={submit}/><Text style={s.helper}>No password needed. Your one-time code will arrive by email.</Text><Text style={s.authFoot}>New to Fitora? <Text style={s.link} onPress={() => navigation.navigate('Register')}>Create account</Text></Text></AuthShell>;
};

export const RegisterScreen = ({ navigation }: P<'Register'>) => {
  const { requestSignupOtp } = useAuth(); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const [firstName, setFirstName] = useState(''); const [email, setEmail] = useState(''); const [phone, setPhone] = useState('');
  const submit = async () => { const normalizedEmail = email.trim().toLowerCase(); if (!firstName.trim() || !normalizedEmail || !phone.trim()) { setError('Complete all three fields.'); return; } if (!/^\S+@\S+\.\S+$/.test(normalizedEmail)) { setError('Enter a valid email address.'); return; } if (phone.replace(/\D/g, '').length < 10) { setError('Enter a valid mobile number.'); return; } setBusy(true); setError(''); try { await requestSignupOtp({ firstName, email: normalizedEmail, phone }); navigation.replace('VerifyEmailOtp', { email: normalizedEmail, mode: 'signup' }); } catch (e) { setError(messageOf(e)); } finally { setBusy(false); } };
  return <AuthShell title="Create account" subtitle="Three details, then verify your email." onBack={() => navigation.goBack()}><AppInput label="First name" placeholder="Your first name" value={firstName} onChangeText={setFirstName} autoComplete="given-name"/><AppInput label="Email" placeholder="you@example.com" value={email} onChangeText={setEmail} keyboardType="email-address" autoCapitalize="none" autoComplete="email"/><AppInput label="Mobile number" placeholder="+91 00000 00000" value={phone} onChangeText={setPhone} keyboardType="phone-pad" autoComplete="tel"/>{!!error && <Text style={s.error}>{error}</Text>}<AppButton title={busy ? 'Sending code…' : 'Continue with email OTP'} disabled={busy} onPress={submit}/><Text style={s.helper}>By continuing, you agree to Fitora’s Terms and Privacy Policy.</Text><Text style={s.authFoot}>Already a member? <Text style={s.link} onPress={() => navigation.navigate('Login')}>Log in</Text></Text></AuthShell>;
};

export const VerifyEmailOtpScreen = ({ navigation, route }: P<'VerifyEmailOtp'>) => {
  const { verifyEmailOtp, resendEmailOtp } = useAuth(); const [otp, setOtp] = useState(''); const [busy, setBusy] = useState(false); const [resending, setResending] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const submit = async () => { if (!/^\d{6,8}$/.test(otp)) { setError('Enter the verification code from your email.'); return; } setBusy(true); setError(''); try { await verifyEmailOtp(route.params.email, otp); } catch (e) { setError(messageOf(e)); } finally { setBusy(false); } };
  const resend = async () => { setResending(true); setError(''); setNotice(''); try { await resendEmailOtp(route.params.email, route.params.mode); setNotice('A new verification code was sent.'); } catch (e) { setError(messageOf(e)); } finally { setResending(false); } };
  const returnScreen = route.params.mode === 'login' ? 'Login' : 'Register';
  return <AuthShell title={route.params.mode === 'login' ? 'Enter your login code' : 'Verify your email'} subtitle={`Enter the code sent to ${route.params.email}`} onBack={() => navigation.navigate(returnScreen)}><AppInput label="One-time code" placeholder="000000" value={otp} onChangeText={value => setOtp(value.replace(/\D/g, '').slice(0, 8))} keyboardType="number-pad" autoComplete="one-time-code" textContentType="oneTimeCode" maxLength={8}/>{!!notice && <Text style={s.success}>{notice}</Text>}{!!error && <Text style={s.error}>{error}</Text>}<AppButton title={busy ? 'Verifying…' : route.params.mode === 'login' ? 'Verify and log in' : 'Verify and create account'} disabled={busy || resending} onPress={submit}/><AppButton title={resending ? 'Sending…' : 'Resend code'} variant="ghost" disabled={busy || resending} onPress={resend}/><Text style={s.authFoot}>Wrong email? <Text style={s.link} onPress={() => navigation.navigate(returnScreen)}>Go back</Text></Text></AuthShell>;
};

const s = StyleSheet.create({ safe: { flex: 1 }, center: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 8 }, logo: { width: 76, height: 76, borderRadius: 25, alignItems: 'center', justifyContent: 'center', marginBottom: 8 }, logoSmall: { width: 37, height: 37, borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, brand: { fontSize: 29, fontWeight: '900', letterSpacing: 3 }, brandWhite: { color: '#fff', fontSize: 20, fontWeight: '900', letterSpacing: 2 }, loader: { width: 110, height: 4, borderRadius: 4, overflow: 'hidden', marginTop: 32 }, overlay: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(7,7,6,.42)' }, welcome: { flex: 1, justifyContent: 'space-between', paddingHorizontal: 22, paddingVertical: 20 }, brandRow: { flexDirection: 'row', alignItems: 'center', gap: 9 }, heroTitle: { color: '#fff', fontSize: 43, lineHeight: 47, fontWeight: '900', letterSpacing: -1.4, maxWidth: 340 }, heroCopy: { color: 'rgba(255,255,255,.82)', fontSize: 16, lineHeight: 24, maxWidth: 335 }, form: { padding: 22, gap: 18, flexGrow: 1 }, link: { color: '#F36B21', fontWeight: '800' }, authFoot: { textAlign: 'center', color: '#777772', marginTop: 4 }, helper: { textAlign: 'center', color: '#8A8A84', fontSize: 12, lineHeight: 18, paddingHorizontal: 12 }, error: { color: '#E74C3C', fontSize: 13, lineHeight: 18 }, success: { color: '#27A66B', fontSize: 13, fontWeight: '700' } });
