import { Ionicons } from '@expo/vector-icons';
import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { VideoView, useVideoPlayer } from 'expo-video';
import React, { useState } from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { AmbientBackground, AppButton, AppHeader, AppInput, EmptyState, GlassCard, StatusBadge } from '../components/ui';
import { useAuth } from '../context/AuthContext';
import { useCatalog } from '../context/CatalogContext';
import { useAppTheme } from '../context/ThemeContext';
import { RootStackParamList } from '../types';

type P<N extends keyof RootStackParamList> = NativeStackScreenProps<RootStackParamList, N>;
const Shell = ({ children }: React.PropsWithChildren) => { const { theme } = useAppTheme(); return <SafeAreaView style={{ flex: 1, backgroundColor: theme.background }}><AmbientBackground/><ScrollView contentContainerStyle={s.page}>{children}</ScrollView></SafeAreaView>; };

export const PlanDetailsScreen = ({ navigation, route }: P<'PlanDetails'>) => {
  const { theme } = useAppTheme(); const { plans, hasActivePackage } = useCatalog();
  const plan = plans.find(item => item.id === route.params.planId);
  if (!plan) return <Shell><AppHeader title="Package" back onBack={() => navigation.goBack()}/><EmptyState title="This package is not available."/></Shell>;
  const active = hasActivePackage(plan.id);
  return <Shell><AppHeader title={plan.name} subtitle="Program details" back onBack={() => navigation.goBack()}/><GlassCard><Text style={[s.price, { color: theme.text }]}>₹{plan.price}<Text style={{ fontSize: 16, color: theme.muted }}> / {plan.duration}</Text></Text><Text style={{ color: theme.muted, marginTop: 5 }}>{plan.description}</Text></GlassCard><Text style={[s.heading, { color: theme.text }]}>What’s included</Text>{plan.benefits.map(item => <View key={item} style={s.check}><Ionicons name="checkmark-circle" size={22} color={theme.accent}/><Text style={{ color: theme.text, fontWeight: '600' }}>{item}</Text></View>)}{active && <StatusBadge label="Your active package" tone="success"/>}<AppButton disabled={active} title={active ? 'Already active' : 'Continue to dummy checkout'} onPress={() => navigation.navigate('Checkout', { planId: plan.id })}/></Shell>;
};

export const CheckoutScreen = ({ navigation, route }: P<'Checkout'>) => {
  const { theme } = useAppTheme(); const { plans, activateDummySubscription } = useCatalog();
  const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const plan = plans.find(item => item.id === route.params.planId);
  if (!plan) return <Shell><AppHeader title="Checkout" back onBack={() => navigation.goBack()}/><EmptyState title="This package is not available."/></Shell>;
  const complete = async () => { setBusy(true); setError(''); try { await activateDummySubscription(plan.id); navigation.replace('PaymentSuccess', { planId: plan.id }); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to activate this package.'); } finally { setBusy(false); } };
  return <Shell><AppHeader title="Dummy checkout" subtitle="Review your test order." back onBack={() => navigation.goBack()}/><GlassCard><View style={s.row}><View style={{ flex: 1 }}><Text style={[s.heading, { color: theme.text }]}>{plan.name}</Text><Text style={{ color: theme.muted }}>{plan.duration} access</Text></View><Text style={[s.priceSmall, { color: theme.text }]}>₹{plan.price}</Text></View></GlassCard><GlassCard><Text style={[s.heading, { color: theme.text }]}>Order summary</Text><View style={s.line}><Text style={{ color: theme.muted }}>Package price</Text><Text style={{ color: theme.text }}>₹{plan.price}</Text></View><View style={s.line}><Text style={{ color: theme.muted }}>Payment mode</Text><Text style={{ color: theme.text }}>Test only</Text></View><View style={[s.line, { borderTopWidth: 1, borderColor: theme.border, paddingTop: 14 }]}><Text style={{ color: theme.text, fontWeight: '900' }}>Total</Text><Text style={[s.priceSmall, { color: theme.text }]}>₹{plan.price}</Text></View></GlassCard><View style={s.secure}><Ionicons name="information-circle" size={20} color={theme.accent}/><Text style={{ color: theme.muted, flex: 1 }}>This is a dummy checkout. No real payment will be charged.</Text></View>{!!error && <Text style={{ color: theme.danger, textAlign: 'center' }}>{error}</Text>}<AppButton disabled={busy} title={busy ? 'Activating…' : 'Complete dummy checkout'} icon="checkmark-circle" onPress={complete}/></Shell>;
};

export const PaymentSuccessScreen = ({ navigation, route }: P<'PaymentSuccess'>) => { const { theme } = useAppTheme(); const { plans } = useCatalog(); const plan = plans.find(item => item.id === route.params.planId); return <Shell><View style={s.state}><View style={[s.stateIcon, { backgroundColor: theme.success + '18' }]}><Ionicons name="checkmark" size={45} color={theme.success}/></View><Text style={[s.stateTitle, { color: theme.text }]}>Package activated</Text><Text style={[s.stateCopy, { color: theme.muted }]}>Your {plan?.name ?? 'selected'} package is active. Its Mux videos are now unlocked.</Text><StatusBadge label={`${plan?.name ?? 'Package'} · Active`} tone="success"/></View><AppButton title="Watch workouts" onPress={() => navigation.replace('Main')}/></Shell>; };
export const PaymentFailedScreen = ({ navigation, route }: P<'PaymentFailed'>) => { const { theme } = useAppTheme(); return <Shell><View style={s.state}><View style={[s.stateIcon, { backgroundColor: theme.danger + '18' }]}><Ionicons name="close" size={45} color={theme.danger}/></View><Text style={[s.stateTitle, { color: theme.text }]}>Activation failed</Text><Text style={[s.stateCopy, { color: theme.muted }]}>We couldn’t activate this package. No amount was charged.</Text></View><AppButton title="Try again" onPress={() => navigation.replace('Checkout', { planId: route.params.planId })}/></Shell>; };

export const VideoDetailsScreen = ({ navigation, route }: P<'VideoDetails'>) => {
  const { theme } = useAppTheme(); const { videos } = useCatalog(); const video = videos.find(item => item.id === route.params.videoId);
  const source = video?.muxPlaybackId ? { uri: `https://stream.mux.com/${video.muxPlaybackId}.m3u8` } : null;
  const player = useVideoPlayer(source, instance => { instance.loop = false; });
  if (!video) return <Shell><AppHeader title="Workout" back onBack={() => navigation.goBack()}/><EmptyState title="This video is locked or unavailable. Activate its package to watch it."/><AppButton title="Browse packages" onPress={() => navigation.navigate('Main')}/></Shell>;
  return <Shell><AppHeader title="Workout" back onBack={() => navigation.goBack()}/><VideoView style={s.player} player={player} nativeControls allowsFullscreen allowsPictureInPicture/><View style={s.row}><View style={{ flex: 1 }}><Text style={[s.videoTitle, { color: theme.text }]}>{video.title}</Text><Text style={{ color: theme.muted, marginTop: 5 }}>{video.category} · {video.duration}</Text></View><StatusBadge label="Unlocked" tone="success"/></View><Text style={[s.heading, { color: theme.text }]}>With {video.trainer}</Text><Text style={{ color: theme.muted, lineHeight: 23 }}>{video.description || 'Follow the trainer at your own pace and listen to your body.'}</Text></Shell>;
};

export const LockedContentScreen = ({ navigation }: P<'LockedContent'>) => { const { theme } = useAppTheme(); return <Shell><AppHeader title="Workout locked" back onBack={() => navigation.goBack()}/><GlassCard style={{ alignItems: 'center', gap: 12 }}><View style={[s.lockCircle, { backgroundColor: theme.accentSoft }]}><Ionicons name="lock-closed" size={28} color={theme.accent}/></View><Text style={[s.stateTitle, { color: theme.text, fontSize: 25 }]}>Subscription required</Text><Text style={[s.stateCopy, { color: theme.muted }]}>Activate the matching package to unlock its videos.</Text></GlassCard><AppButton title="Browse packages" onPress={() => navigation.navigate('Main')}/></Shell>; };

export const EditProfileScreen = ({ navigation }: P<'EditProfile'>) => { const { theme } = useAppTheme(); const { profile, user, updateProfile } = useAuth(); const [fullName, setFullName] = useState(profile?.full_name || ''); const [phone, setPhone] = useState(profile?.phone || ''); const [saved, setSaved] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const save = async () => { if (!fullName.trim()) { setError('Full name is required.'); return; } setBusy(true); setError(''); setSaved(false); try { await updateProfile({ full_name: fullName, phone: phone || null }); setSaved(true); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to save your profile.'); } finally { setBusy(false); } }; return <Shell><AppHeader title="Edit profile" subtitle="Keep your details current." back onBack={() => navigation.goBack()}/><AppInput label="Full name" value={fullName} onChangeText={setFullName}/><AppInput label="Email" value={profile?.email || user?.email || ''} editable={false} keyboardType="email-address"/><Text style={{ color: theme.muted, fontSize: 12, marginTop: -14 }}>Email is managed by your account and cannot be edited here.</Text><AppInput label="Phone" value={phone} onChangeText={setPhone} keyboardType="phone-pad"/>{!!error && <Text style={{ color: theme.danger, textAlign: 'center' }}>{error}</Text>}<AppButton title={busy ? 'Saving…' : saved ? 'Changes saved' : 'Save changes'} icon={saved ? 'checkmark' : undefined} disabled={busy} onPress={save}/>{saved && <Text style={{ color: theme.success, textAlign: 'center' }}>Your shared profile has been updated.</Text>}</Shell>; };

const s = StyleSheet.create({ page: { paddingHorizontal: 20, paddingTop: 18, paddingBottom: 38, gap: 22, flexGrow: 1 }, price: { fontSize: 38, fontWeight: '900' }, priceSmall: { fontSize: 23, fontWeight: '900' }, heading: { fontSize: 19, fontWeight: '900', marginTop: 2 }, check: { flexDirection: 'row', alignItems: 'center', gap: 11, paddingVertical: 2 }, row: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 }, line: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 8 }, secure: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 8 }, state: { flex: 1, minHeight: 420, alignItems: 'center', justifyContent: 'center', gap: 16 }, stateIcon: { width: 92, height: 92, borderRadius: 32, alignItems: 'center', justifyContent: 'center' }, stateTitle: { fontSize: 31, fontWeight: '900', textAlign: 'center', letterSpacing: -.7 }, stateCopy: { fontSize: 16, lineHeight: 24, textAlign: 'center', maxWidth: 330 }, player: { width: '100%', height: 235, borderRadius: 26, overflow: 'hidden', backgroundColor: '#111' }, videoTitle: { fontSize: 29, fontWeight: '900', letterSpacing: -.8 }, lockCircle: { width: 62, height: 62, borderRadius: 22, alignItems: 'center', justifyContent: 'center' } });
